name: CI Checks

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        python-version: "3.9"

    - nmae: install dependencies
      run: |
        pip istall -r requirements.txt
